name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    strategy:
      matrix:
        directories: [vmm/sandbox, vmm/task, shim, wasm, quark]
        include:
          - directories: wasm
            wasmEdge: 0.11.2
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install nightly --component rustfmt
      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install WasmEdge
        if: ${{ matrix.wasmEdge }}
        run: curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v ${{ matrix.wasmEdge }} >> /dev/null
      - name: Check
        working-directory: ${{ matrix.directories }}
        run: cargo check --examples --tests --all-features
      - name: Nightly fmt
        working-directory: ${{ matrix.directories }}
        run: cargo +nightly fmt --all -- --check
      - name: Clippy
        working-directory: ${{ matrix.directories }}
        run: cargo clippy --all-features -- -D warnings
      - name: Deny
        working-directory: ${{ matrix.directories }}
        run: cargo install cargo-deny && cargo deny -L warn --all-features check


  tests:
    strategy:
      matrix:
        directories: [ vmm/sandbox, vmm/task, shim, wasm, quark ]
        include:
          - directories: wasm
            wasmEdge: 0.11.2
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install WasmEdge
        if: ${{ matrix.wasmEdge }}
        run: curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v ${{ matrix.wasmEdge }} >> /dev/null
      - name: Test
        working-directory: ${{ matrix.directories }}
        run: RUST_BACKTRACE=1 RUST_BACKTRACE=full sudo -E $(command -v cargo) test --all-features
        